### ISSUE TITLE
"NoUnused.Dependencies" reports "elm/json"

### ISSUE THREAD

**Issue by PedroHLC** [jfmengels/elm-review-unused#30]
## Describe the bug
When running `npx elm-review --template PaackEng/elm-review-config src`:
> NoUnused.Dependencies: Unused dependency `elm/json`

After removing `elm/json`, `elm make src/Main.elm` throws:
> I need to see an "elm/json" dependency your elm.json file.

## SSCCE (Short Self-Contained Correct Example)
```bash
git clone 'https://github.com/PaackEng/paack-ui.git' -b wms-802-listview-checkbox
cd paack-ui/showcase
npx elm-review --template PaackEng/elm-review-config src
```

## Expected behavior
Never suggest `elm/json` as unused.

## Additional context
We actually never noticed a lot of false-positives, then "something" changed, and to reflect, we made some changes in the GH action. Now, we're pursued by this bug. I suspect [this is the change](https://discourse.elm-lang.org/t/you-thought-you-had-no-dead-code/7145).

**Comment by jfmengels** [comment]
Hello :wave:

I took a look at the project, and don't think this is actually a bug. I'll explain:

## Why you're getting this false positive

`elm-review`'s rules look at the entire project and reports errors based on what it saw. The `NoUnused.Dependencies` rule looks at all the Elm files, and if it doesn't see any imports of the modules from `elm/json`, reports that `elm/json` is unused.

The problem here, is that you are **not** passing the whole project, because you are telling `elm-review` to only look at `src`, while the project is comprised of both `src` AND `../src`.

Running `elm-review src` means that it should only look at files in `src` and **not** that it should only report errors for `src`.

The right way to call `elm-review` is without passing directories to it, making it look at all the "source-directories" and "tests/". The option exists mostly to support projects where tests are not in a "tests/" directory.

So in this case, `elm.json` is only used in `../src`, so it is normal that the rule considers `elm/json` to be unused. When I run `elm-review` without specifying a directory, the false positive disappears, though I'm getting issues for things `../src`.

`elm-review` doesn't support looking at 2 projects (2 elm.json) at once, because I haven't figured a good solution for that. My understanding is that you ran with `src` in order to not get the reported errors for `../src`, and that's not really the way to go.

## Side-note on the usage of --template

So it seems you like to use `--template` for your configuration. That is to be honest not what I intended it to be used for (it was mostly for trying things out temporarily), and I would recommend against it for 2 reasons:
- If you change your configuration, then some projects' build may start to fail (a spooky action at a distance)
- It becomes very tricky to add exceptions using `Rule.ignoreErrorsFor*` functions, or even new rules you'd like to enable only for a specific project.
- You can get GitHub rate limit issues

My personal advice would be to periodically run `elm-review init --template PaackEng/elm-review-config` to update your configuration, or even to have an automated job do that and make a PR once in a while. It's more tedious but builds will fail in less "magical" way.

That said, if you're fine with the trade-offs I mentioned, then by all means continue to do so!

## Suggestions for a solution

The solution to your problem is to stop passing `src` to `elm-review`. That will unfortunately add the new issue that you'll have reports for "../src".

I suggest two solutions:
1) Use `init` as suggested above to commit a configuration, then at the end of your configuration, do this
```elm
config =
  [ -- rule1
  , -- rule2
  , -- ...
  ]
  |> List.map (Rule.ignoreErrorsForDirectories [ "../src" ])
```

That way, the project will be seen in its entirety, but the errors for `../src` will be ignored.

2) Wait a few days, and use the `--ignore-dirs` flag (`elm-review --ignore-dirs src`) that I just so happened to add recently but haven't yet released.

I think you'll be more happy with 2) though.

I think you'll be happy with one of these 2 solutions, and since I don't think this is an actual issue (feel free to comment if you disagree), I'll close the issue.

> We actually never noticed a lot of false-positives

Version 1.1.5 had a lot of changes and from the reports I get, a few bugs. Sorry if you ran into some :bow:
I am myself disappointed with the false positives that were found 

I plan on releasing a patch for those bugs in the next days, maybe even tomorrow (Friday) based on feedback I get about a remaining issue. That said, I am pretty sure this new version has **not** impacted the behavior for this rule, so I think your configuration may have changed in a different way :thinking:

This turned out to be a mouthful, sorry :sweat_smile:
