### ISSUE TITLE
Unused type aliases not detected

### ISSUE THREAD

**Issue by smucode** [jfmengels/elm-review-unused#48]
In certain files, unused type aliases are not detected. It doesn't matter what the variable name is, or what type it is an alias for, no unused type alias are reported. Other things like unused custom type definitions seem to work fine.

We have a large project so haven't been able to SSCCE. Neither been able to see a pattern of which files it works for, and which it doesn't...

Any idea what might cause this, to help us narrow it down perhaps?

**Comment by jfmengels** [comment]
Hi @smucode :wave:

Have you confirmed that your code still compiles and tests still pass if you remove the type alias?

Can you clarify what rule you're expecting to report an issue for?
If it's `NoUnused.Exports`, then the issue could be that your module is exposing everything (`module A exposing (..)` but the value is still used inside the module.

But I'm guessing you're talking about `NoUnused.Variables`. Again, check that the value is not exposed through `exposing (..)`, because the rule lets `NoUnused.Exports` assume the role of cleaning up what's exposed, while it focuses on local definitions.

So I'd check
- whether the value is really unused by trying to remove it
- Checking whether the module is exposing everything
- (and the obvious: check that you're using the latest version of this package)

If the problem is not in the above, then it could indeed be a bug in the package (which would be cool, because we'd report even more things! :tada: ). In that case, I'd look at whether you have similarly named types somewhere else, and check whether renaming one of the types changes anything.

Thanks for opening the issue :)

**Comment by smucode** [comment]
> Whether the value is really unused by trying to remove it

Yep, adding something with a random name isn't detected

> Checking whether the module is exposing everything

It is not, we disallow that.

> Check that you're using the latest version of this package

We were on 1.1.11 🤦 But I upgraded to 1.1.16 (❤️  `--fix-all`) and i still see problems, but slightly different.

Now unused type aliases where the value is a record, are always detected it seems. But, type aliases where the value is a String or Int, are never detected...

So I can go to some random file and add something like `type alias ThisNameIsUsedNowhereElse = Int` and it's not detected. If i change it to `type alias ThisNameIsUsedNowhereElse = {}`, it is detected...

**Comment by jfmengels** [comment]
Aha, that helps a lot!

I just checked, and indeed, the rule only reports type aliases that alias a record. That is a recent change because of some issue around imported types with the same name.

I'll see if I can fix this before going on holidays, thanks for helping out figure the issue :heart:
