### ISSUE TITLE
NoUnused.Variables reports an alias as unused, but it's used

### ISSUE THREAD

**Issue by miniBill** [jfmengels/elm-review-unused#89]
**Describe the bug**
```elm
import Generated.Types as Types exposing (Faction)
import Types exposing (Choice)

foo = Types.factionFromString "..."
```

`factionFromString` is coming from `Generated.Types`, so the alias is not redundant, and telling me to remove it is a false positive.

**Comment by jfmengels** [comment]
I know it's possible for `elm-review` to get this incorrect when it can't actually find some of the files. Do you know if you by any chance ran `elm-review` with the `Generated.Types` being absent from the source code? I believe that having it be present would solve the problem here.

If that's not the case, could you possibly create a SSCCE for this? Or at least some kind of reproducible case.

**Comment by miniBill** [comment]
Ah, yeah, I think that may have happened because elm-review ran while elm-codegen was creating that file, so it would have been missing. I can't actually reproduce it now, so a race condition seems likely :(

Sorry for the false alarm.
